image: python:3.9-slim

variables:
  GIT_SUBMODULE_STRATEGY: recursive
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip/"

stages:
  - build
  - test
  - deploy

# Pip's cache doesn't store the python packages
# https://pip.pypa.io/en/stable/reference/pip_install/#caching
#
# If you want to also cache the installed packages, you have to install
# them in a virtualenv and cache it as well.
cache:
  - key:
      files:
        - requirements.txt
    paths:
      - venv/
      - .cache/pip

before_script:
  - python -m venv --upgrade-deps venv/
  - source venv/bin/activate
  - python -m pip install -r requirements.txt

test:
  # Remove this tag if you want to use GitLab shared runners instead
  tags:
    - md705
  stage: test
  script:
    - python smalltest.py

run-all:
  # Remove this tag if you want to use GitLab shared runners instead
  tags:
    - md705
  stage: test
  # Scheduled run only since this job would take 6 hours on our 32-core machine
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
  script:
    - python run.py
  artifacts:
    paths:
      - data/*.txt
