name: CI

on:
  push:
    branches: [main]
    # Publish semver tags as releases.
    tags: ["*.*"]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      UV_SYSTEM_PYTHON: 1
    steps:
      - uses: actions/checkout@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.x'
      - name: Install uv
        run: curl -LsSf https://astral.sh/uv/install.sh | sh
      - name: Install Python dependencies
        run: uv pip install -r requirements.txt
      - name: Run Test
        run: uv run smalltest.py
